name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2       
    - name: Setup .net core 3.1.405
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 3.1.405
    - name: Setup .net core 5.0.102
      uses: actions/setup-dotnet@v1
      with:
       dotnet-version: 5.0.102
    - name: .net SxS
      run: |
       rsync -a ${DOTNET_ROOT/5.0.102/3.1.405}/* $DOTNET_ROOT/  
    - name: Install Roslynator
      run: dotnet tool install --global Roslynator.DotNet.Cli --version 0.1.1
    - name: install Dotnet Grab
      run: dotnet tool install --global dotnet-grab --version 0.1.1
    - name: Grab
      run:  grab Roslynator.Analyzers@3.1.0-rc
    - name: Restore dependencies
      run: dotnet restore ./src/test
    - name: Build
      run: dotnet build ./src/test --no-restore
    - name: Analyze
      run: roslynator analyze ./src/test/test.sln
