name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install Roslynator.DotNet.Cli
      run: dotnet tool install --global Roslynator.DotNet.Cli --version 0.1.1
    - name: Analyze
      run: roslynator analyze ./src/test/test.sln
    - name: Restore dependencies
      run: dotnet restore ./src/test
    - name: Build
      run: dotnet build ./src/test --no-restore
